package utils;

public interface RequestInfor {
    String REGISTER = "REGISTER";
    String REGISTERED = "REGISTERED";
    String SHARE = "SHARE";
    String SEARCH = "SEARCH";
    String QUERY = "QUERY";
    String GET_CHUNK = "GET_CHUNK";
    String FILE_INFO = "FILE_INFO";
    String FILE_NOT_FOUND = "FILE_NOT_FOUND";
    String PONG = "PONG";
    String SHARED_LIST = "SHARED_LIST";
    String PING = "PING";
    String SHARE_LIST = "LSHARE";
    String UNSHARED_FILE = "UNSHARED_FILE";
    String REFRESH = "REFRESH";
    String REFRESHED = "REFRESHED";
    String GET_PEERS = "GET_PEERS";
    String NOT_FOUND = "NOT_FOUND";
    String SHARE_TO_PEERS = "SHARE_TO_PEERS";
    String GET_SHARED_PEERS = "GET_SHARED_PEERS";
    String GET_KNOWN_PEERS = "GET_KNOWN_PEERS";
    String PUBLIC_KEY = "PUBLIC_KEY";
    String PUBLIC_KEY_RESP = "PUBLIC_KEY_RESP";
    String PEER_NOT_FOUND = "PEER_NOT_FOUND";
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String SEND_MSG = "SEND_MSG";
    String SEND_MSG_RESP = "SEND_MSG_RESP";
    String MESSAGE_ERROR = "MESSAGE_ERROR";
    String GET_OFFLINE_MSGS = "GET_OFFLINE_MSGS";
    String OFFLINE_MSGS_RESP = "OFFLINE_MSGS_RESP";
    String ACK_OFFLINE_MSGS = "ACK_OFFLINE_MSGS";
    String ACK_OFFLINE_MSGS_RESP = "ACK_OFFLINE_MSGS_RESP";
    String ALL_PEER = "ALL_PEER";
    String ALL_PEER_RESP = "ALL_PEER_RESP";
    String ALL_PEER_INFO = "ALL_PEER_INFO";
    String ALL_PEER_INFO_RESP = "ALL_PEER_INFO_RESP";
    String PEER_INFO = "PEER_INFO";
    String PEER_INFO_RESP = "PEER_INFO_RESP";

    // SSL/TLS Constants
    int SSL_PORT_OFFSET = 1000;
}
