# Database configuration
db.url=jdbc:sqlite:p2p_chat.db
# Hibernate connection configuration
hibernate.connection.driver_class=org.sqlite.JDBC
hibernate.connection.url=jdbc:sqlite:p2p_chat.db
hibernate.connection.pool_size=5
# Hibernate configuration
hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=false
hibernate.format_sql=true



